[workspace]
members = [
  "examples/server",
  "./crates/voxelize",
  "./crates/voxelize-actix",
  "./crates/voxelize-events",
  "./crates/voxelize-protocol"
]
resolver = "2"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1

